language: android

env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23

 
before_script:
  # Create and start emulator

  - adb shell input keyevent 82 &


notifications:
  email:true

script: 
   ./gradlew connectedAndroidTest